/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.davils.buildsrc.iconize.generation.writer

import com.davils.buildsrc.iconize.generation.GenerationContext
import com.squareup.kotlinpoet.FileSpec
import java.io.File

/**
 * Fixed notice prepended to every generated file to warn maintainers that
 * manual edits will be overwritten on the next generator run.
 *
 * @since 1.0.0
 */
private const val AUTO_GENERATED_NOTICE: String =
    "AUTO-GENERATED FILE. DO NOT EDIT.\n" +
        "This file was generated by the Iconize Gradle plugin.\n" +
        "Any manual changes will be overwritten the next time the generator runs."

/**
 * Contract for a single Kotlin source file generator.
 *
 * Implementations build a [FileSpec] via KotlinPoet and write it to the
 * configured source root under [targetPackage].
 *
 * @since 1.0.0
 */
internal interface FileWriter {
    /**
     * Resolves the simple file name (without extension) for the given [context].
     *
     * @param context The [com.davils.buildsrc.iconize.generation.GenerationContext] with all input data.
     * @return The simple name of the file to generate.
     * @since 1.0.0
     */
    fun fileName(context: GenerationContext): String

    /**
     * Resolves the fully-qualified target package for the generated file.
     *
     * Defaults to [GenerationContext.targetPackage].
     *
     * @param context The [GenerationContext] with all input data.
     * @return The target package of the generated file.
     * @since 1.0.0
     */
    fun targetPackage(context: GenerationContext): String = context.targetPackage

    /**
     * Whether the file should be regenerated when it already exists.
     *
     * Files that are shared across multiple icon packs (e.g. `LumeIcon`) should
     * return `false` so that they are only generated once.
     *
     * @return `true` if the existing file should be overwritten, `false` otherwise.
     * @since 1.0.0
     */
    fun overwriteIfExists(): Boolean = true

    /**
     * Builds the [FileSpec] that represents the generated file.
     *
     * @param context The [GenerationContext] with all input data.
     * @return The fully built [FileSpec].
     * @since 1.0.0
     */
    fun buildFileSpec(context: GenerationContext): FileSpec

    /**
     * Writes the generated source to the configured source root.
     *
     * @param context The [GenerationContext] with all input data.
     * @since 1.0.0
     */
    fun write(context: GenerationContext) {
        val target = outputFile(context)
        if (target.exists() && !overwriteIfExists()) return

        val spec = buildFileSpec(context)
        spec.writeTo(context.sourceRoot)
        prependHeader(target, context)
    }

    /**
     * Prepends the copyright header (if any) and the auto-generated notice to
     * the already-written [target] file.
     *
     * A blank line separates the copyright from the notice and another blank
     * line separates the full header from the `package` declaration, producing
     * a clean, readable layout that KotlinPoet does not emit on its own.
     *
     * @param target The file previously written by KotlinPoet.
     * @param context The [GenerationContext] providing the optional copyright.
     * @since 1.0.0
     */
    private fun prependHeader(target: File, context: GenerationContext) {
        if (!target.isFile) return
        val header = buildString {
            context.copyright?.takeIf { it.isNotBlank() }?.let { copyright ->
                copyright.lineSequence().forEach { line ->
                    append("// ").append(line).append('\n')
                }
                append("//\n")
            }
            AUTO_GENERATED_NOTICE.lineSequence().forEach { line ->
                append("// ").append(line).append('\n')
            }
            append('\n')
        }
        val text = target.readText()
        val withoutLeadingBlank = text.trimStart('\n', ' ')
        target.writeText(header + withoutLeadingBlank)
    }

    /**
     * Deletes the previously generated file if it exists and [overwriteIfExists] is `true`.
     *
     * @param context The [GenerationContext] with all input data.
     * @since 1.0.0
     */
    fun cleanPrevious(context: GenerationContext) {
        if (!overwriteIfExists()) return
        val file = outputFile(context)
        if (file.exists()) file.delete()
    }

    /**
     * Resolves the absolute file location this writer will produce.
     *
     * The path is derived from [GenerationContext.sourceRoot], the writer's
     * [targetPackage] and [fileName].
     *
     * @param context The [GenerationContext] with all input data.
     * @return The absolute file where this writer produces its output.
     * @since 1.0.0
     */
    private fun outputFile(context: GenerationContext): File {
        val packageDir = File(context.sourceRoot, targetPackage(context).replace('.', '/'))
        return File(packageDir, "${fileName(context)}.kt")
    }
}
