/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package colors.palettes

import colors.model.LumenColorFamily
import colors.model.LumenColors
import colors.model.ThemeVariant
import colors.pattern.PaletteSource
import colors.utils.c
import colors.utils.scale

public object TailwindPalette : PaletteSource {
    override val id: String = "tailwind"
    override val name: String = "Tailwind"

    // Needs the Colors: https://tailwindcss.com/docs/colors
    override fun create(variant: ThemeVariant): LumenColors {
        return LumenColors(
            mapOf(
                LumenColorFamily.RED to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.ORANGE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.AMBER to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.YELLOW to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.LIME to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.GREEN to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc), ),
                LumenColorFamily.EMERALD to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.TEAL to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.CYAN to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.SKY to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.BLUE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.INDIGO to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.VIOLET to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.PURPLE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.FUCHSIA to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.PINK to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.ROSE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.SLATE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.GRAY to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.ZINC to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.NEUTRAL to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.STONE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.TAUPE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.MAUVE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.MIST to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                ),
                LumenColorFamily.OLIVE to scale(
                    c50 = c(0xFFFEc),
                    c100 = c(0xFFFEc),
                    c200 = c(0xFFFEc),
                    c300 = c(0xFFFEc),
                    c400 = c(0xFFFEc),
                    c500 = c(0xFFFEc),
                    c600 = c(0xFFFEc),
                    c700 = c(0xFFFEc),
                    c800 = c(0xFFFEc),
                    c900 = c(0xFFFEc),
                    c950 = c(0xFFFEc),
                )
            )
        )
    }
}